Wrote tests for blocked_actions_sleep, fixed protection not working
ohld/igbot pull request #1093
Opened 2019-10-19 15:37 UTC by leoccyao

This pr started with me trying to write tests for the recently added blocked_actions_sleep functionality; however, upon finding the tests failing, I found that the api send_request() method was not returning "feedback_required" upon hitting a block (see https://github.com/instagrambot/instabot/issues/1087#issuecomment-542549855). Therefore, a second commit was added to reinstate the return value of "feedback_required" (which was present in an earlier version, but seemed to have been removed somewhere).

2019-10-19 16:35 UTC, madshansens commented
sorry to say but the sleep patterns has been tested for months and does only have very little impact.

2019-10-19 21:38 UTC, leoccyao commented
The code coverage report seems to confirm that, with this PR, the blocked actions protection (and sleep delays written before) seems to be hit instead of missed as it was previously.

2019-10-20 08:32 UTC, ohld requested changes
Please read my comments. Mind this PR: https://github.com/instagrambot/instabot/pull/1083

2019-10-20 08:32 UTC, ohld commented on instabot/api/api.py
> +                    return "feedback_required"
Why have you added it back? This is bug and should be removed.

2019-10-20 08:32 UTC, ohld commented on instabot/api/api.py
> +                    return "feedback_required"
You shouldn’t include back this line!

2019-10-20 13:35 UTC, leoccyao commented
I understand that adding this return value of feedback_required breaks the interactive 2FA. However, the blocked actions protection checks for a return value of "feedback_required" to protect against blocks. Without returning "feedback_required", the blocked_actions_protection does not seem to work (always missed in code coverage)

Perhaps place the check for interactive 2FA ahead of the general check for "feedback_required"?

2019-10-21 09:23 UTC, ohld commented
hmm, this history around "feedback_required" tells be that current logic is shitcode. May I ask you to refactor it and also cover it with tests? That would be really awesome.

2019-10-21 22:39 UTC, reliefs commented
feedback_required is used for block protection, i think many packages relying on this "feedback_required" for their bots, as a protection. So to delete this would break many packages include mine if i updated.

Too many feedback_required in a row = ban/action blocked

2019-10-23 02:20 UTC, leoccyao commented
Sure, though I would appreciate some ideas on how to refactor it. For example, should the interactive two-factor authentication be refactored into the login() function? Also, since I don't currently use the 2FA feature, can I request someone else to help write tests for the 2-factor authentication? Thanks.

2019-10-23 11:08 UTC, ohld commented
Guys, please help with your advise on how to refactor login() method to be more robust and scalable. Thanks

2019-10-23 17:58 UTC, madshansens commented
i have seen users ask for 2fa, it's a little niche, but we should have it
to work. But it should not cost breaking already used code.

Remember this package is used by many devs and by breaking this would break
many repos.. highly not suggested to break return feedback_required

Because too many feedback_required = ig blocks you. So somehow this can be
used to avoid blocks.

Den ons. 23. okt. 2019 kl. 13.08 skrev Daniil Okhlopkov <
notifications@github.com>:

> Guys, please help with your advise on how to refactor login() method to be
> more robust and scalable. Thanks
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/instagrambot/instabot/pull/1093?email_source=notifications&email_token=ANE3UC2HTKCFQLRCIZO7Q6TQQAWENA5CNFSM4JCQJN52YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECBAJUI#issuecomment-545391825>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANE3UC7JYHFDGONQBRPDVEDQQAWENANCNFSM4JCQJN5Q>
> .
>

2019-10-24 09:18 UTC, ohld commented
The "feedback_required" return is a bug, check #1083

2019-10-24 22:48 UTC, leoccyao commented
Is it possible to merge in my other changes (tests written for blocked actions protection and utf-8 support in response checking), while also keeping the question of how to refactor feedback_required open? 

I understand that this is currently a failing build, but due to the blocked actions protection not kicking in, it has been for a while - the tests just call attention to that. If you look at the test results, blocked actions protection is never activated, even in the cases where it should be.

For example:
![image](https://user-images.githubusercontent.com/45076643/67530930-b7be4600-f68e-11e9-85a0-7ad6d966ad6d.png)

In this case, the "Your follow action is blocked" should show up, but it doesn't.

2019-10-24 22:50 UTC, leoccyao commented
Updated title of pull request from 
"Wrote tests for blocked_actions_sleep, fixed protection not working" 
to
"New tests for blocked_actions_protection find that it doesn't activate when expected"
to better reflect the changes in this PR.

2019-10-25 09:40 UTC, ohld commented
I definitely can't merge failing build, sorry.

2019-10-26 15:01 UTC, leoccyao commented
The reason why feedback_required was problematic is because the send_request method would exit before getting to the check for 2FA. However, it was also needed, because without it, there is no way to activate blocked actions protection.

This commit adds a second check for 2FA in the login method, after feedback_required is returned. Therefore, if 2FA is needed, even if the send_request method exits with "feedback_required", the interactive 2FA will still activate and the login will still be successful. 

It would be nice to have some tests for 2FA, though.

2019-10-28 17:25 UTC, ohld commented
Ok. You've done a great job here! Thank you really much for your efforts and code. I can't wait for your new pull requests.

2019-10-28 17:25 UTC, ohld approved these changes

2019-10-28 17:25 UTC, ohld commented on instabot/api/api.py
> +                        return "feedback_required"
hmmm, the same "feedback_required" here. The same problem as we had this similar return value. Please prove that this return value is important (please take into account the pull request mentioned above) or just delete it.

2019-10-28 17:26 UTC, merged

2019-10-28 18:14 UTC, patrickrbrandao commented
I'm still getting `feedback_required`This action was blocked...
Do I need to run some of these new tests?