Code cleanup
ohld/igbot pull request #349
Opened 2017-10-05 12:21 UTC by xen

What I purpose with this PR:

- Code simplification, it is little messed in IDE when you see all methods twice
- PEP8 cleanup
- Switch to mixin type of inheritance

I hope it will help to maintain and develop code in future.

2017-10-09 08:41 UTC, sudoguy requested changes
Wrong method resolution order. Method super() can't find right function

2017-10-09 08:41 UTC, sudoguy commented on instabot/bot/bot.py
> +class Bot(API, BotArchive, BotBlock, BotComment, BotDelete,
Wrong method resolution order. API must be in end

2017-10-09 08:41 UTC, sudoguy commented on instabot/bot/bot.py
> +        super(self.__class__, self).__init__()
API init

2017-10-09 08:41 UTC, sudoguy commented on instabot/bot/bot.py
> +        super(self.__class__, self).__init__()
Not ```self.__class__```

2017-10-09 08:41 UTC, sudoguy commented on instabot/bot/bot_archive.py
> +        if super(self.__class__, self).archiveMedia(media, undo):
API class method

2017-10-09 08:41 UTC, sudoguy commented on instabot/bot/bot_block.py
> +            if super(self.__class__, self).block(user_id):
API class method

2017-10-09 08:41 UTC, sudoguy commented on instabot/bot/bot_block.py
> +            if super(self.__class__, self).unblock(user_id):
API class method

2017-10-09 08:41 UTC, sudoguy commented on instabot/bot/bot_comment.py
> +            if super(self.__class__, self).comment(media_id, comment_text):
API class method

2017-10-09 08:41 UTC, sudoguy commented on instabot/bot/bot_delete.py
> +        if super(self.__class__, self).deleteMedia(media):
API class method

2017-10-09 08:41 UTC, sudoguy commented on instabot/bot/bot_direct.py
> +        if super(self.__class__, self).sendDirectItem('message', user_ids, text=text, thread=thread_id):
API class method

2017-10-09 08:41 UTC, sudoguy commented on instabot/bot/bot_direct.py
> +        if super(self.__class__, self).sendDirectItem('media_share', user_ids, text=text, thread=thread_id,
API class method

2017-10-09 08:41 UTC, sudoguy commented on instabot/bot/bot_direct.py
> +        if super(self.__class__, self).sendDirectItem('hashtag', user_ids, text=text, thread=thread_id,
API class method

2017-10-09 08:41 UTC, sudoguy commented on instabot/bot/bot_direct.py
> +        if super(self.__class__, self).sendDirectItem('profile', user_ids, text=text, thread=thread_id,
API class method

2017-10-09 08:41 UTC, sudoguy commented on instabot/bot/bot_direct.py
> +        if super(self.__class__, self).sendDirectItem('like', user_ids, thread=thread_id):
API class method

2017-10-09 08:41 UTC, sudoguy commented on instabot/bot/bot_follow.py
> +            if super(self.__class__, self).follow(user_id):
API class method

2017-10-09 08:41 UTC, sudoguy commented on instabot/bot/bot_like.py
> +            if super(self.__class__, self).like(media_id):
API class method

2017-10-09 08:41 UTC, sudoguy commented on instabot/bot/bot_photo.py
> +        if super(self.__class__, self).uploadPhoto(photo, caption, upload_id):
API class method

2017-10-09 08:41 UTC, sudoguy commented on instabot/bot/bot_photo.py
> +        photo = super(self.__class__, self).downloadPhoto(
API class method

2017-10-09 08:41 UTC, sudoguy commented on instabot/bot/bot_unfollow.py
> +            if super(self.__class__, self).unfollow(user_id):
API class method

2017-10-09 08:41 UTC, sudoguy commented on instabot/bot/bot_unlike.py
> +            if super(self.__class__, self).unlike(media_id):
API class method

2017-10-09 08:41 UTC, sudoguy commented on instabot/bot/bot_video.py
> +        if not super(self.__class__, self).uploadVideo(video, thumbnail, caption):
API class method

2017-10-15 21:23 UTC, ohld commented
@xen Will you fix the issues with the super class? Your pull request is awesome but there are several bugs that should be fixed!

2017-10-18 17:30 UTC, ohld commented
@xen Waiting for your fixes.

2017-10-18 17:30 UTC, closed without merging