handle unhandled error on follow_users method
ohld/igbot pull request #433
Opened 2018-01-05 16:14 UTC by AfshinZlfgh

delay_in_seconds added to delay.py for making delay in wanted time
unhandled error(404 and other errors except 400 and 429) handled in follow_users, 400 and 429 handled in API before.

2018-01-06 13:41 UTC, ohld commented
Thanks for the commit! Can you please fix Travis CI errors and ill merge that

2018-01-07 03:22 UTC, AfshinZlfgh commented
i read Travis CI log and fixed its error, but i cant fix the last one and i dont know its meaning! if you help me and tell how i can fix it, i will fix it. thank you

2018-01-09 13:55 UTC, sudoguy requested changes

2018-01-09 13:55 UTC, sudoguy commented on instabot/bot/bot_follow.py
> +        elif self.LastResponse.status_code != 400 and self.LastResponse.status_code != 429:
Wrong indentation level. Fix to the same level as line 48

2018-01-09 13:55 UTC, sudoguy commented on instabot/bot/bot_follow.py
> +                for i in range(0, try_number):
in python you can use just ```range(try_number)```
start use 0 as default value

2018-01-15 10:07 UTC, sudoguy commented
Closed, because @morozru was resolved all conflicts in https://github.com/instagrambot/instabot/pull/435 based on your decision.
Thanks, @AfshinZlfgh!

2018-01-15 10:07 UTC, closed without merging