Create data_scraper_CLI.py
ohld/igbot pull request #490
Opened 2018-04-10 17:36 UTC by virginsince1997

2018-04-15 15:14 UTC, sudoguy requested changes

2018-04-15 15:14 UTC, sudoguy commented on examples/data_scraper_CLI.py
> +time.sleep(2)
No needs to use delay. If you often use a script, it will be annoying

2018-04-15 15:14 UTC, sudoguy commented on examples/data_scraper_CLI.py
> +time.sleep(2)
The same problem with delay

2018-04-15 15:14 UTC, sudoguy commented on examples/data_scraper_CLI.py
> +    time.sleep(3)
The same problem with delay

2018-04-15 15:14 UTC, sudoguy commented on examples/data_scraper_CLI.py
> +    no = bot.login()
Unused variable

2018-04-15 15:14 UTC, sudoguy commented on examples/data_scraper_CLI.py
> +        time.sleep(3)
The same problem with delay

2018-04-15 15:14 UTC, sudoguy commented on examples/data_scraper_CLI.py
> +    time.sleep(3)
The same problem with delay

2018-04-15 15:14 UTC, sudoguy commented on examples/data_scraper_CLI.py
> +    time.sleep(3)
The same problem with delay

2018-04-15 15:14 UTC, sudoguy commented on examples/data_scraper_CLI.py
> +    time.sleep(3)
The same problem with delay

2018-04-22 08:52 UTC, basnijholt commented
Thanks for the contribution!

I think that this script isn't really useful because there is no way for people to use the scraped data.

Also, I think this whole script can be formulated in 25% of the code.

2018-04-22 08:53 UTC, basnijholt commented on examples/data_scraper_CLI.py
> +        users = bot.get_user_followers(follower,)
You are overwriting `users` each time.

2018-04-22 08:55 UTC, closed without merging