Update bot.py
ohld/igbot pull request #603
Opened 2018-08-02 21:01 UTC by lukasz00500

details in #601 issue

2018-08-05 16:01 UTC, basnijholt commented
Just the user_id does not identify the post, you should also include the media_id

2018-08-05 16:03 UTC, basnijholt commented
Could you also not use camelCase?

2018-08-05 16:24 UTC, lukasz00500 commented
> Just the user_id does not identify the post, you should also include the media_id 

sorry i don't understand can you explain ?

2018-08-08 08:04 UTC, kintaro1981 commented
I think that @basnijholt means that you need the media_id to not like again the same post. Am I right @basnijholt ?

Or @lukasz00500 do you want to simply not like anymore the users at all? I think is better to not like again the same post than stop liking the user forever.

2018-08-12 10:39 UTC, lukasz00500 commented
i want to not like this user anymore -  This is useful when using the function:
like_user_followers
like_user_following
and you cant like all users in one bot session, you do not want to like the same users next day right ?

2018-08-27 21:58 UTC, ohld commented
@lukasz00500 Thank you for the pull request! You have done a great job! 
Please fix your code style according to Python Standards (pep 8) to pass Travis code style tests. Also please add tests that covers your code improvements (this is not obligable).

2018-08-29 20:15 UTC, basnijholt requested changes
Only three lines are relevant in this PR.

2018-08-29 20:15 UTC, basnijholt commented on instabot/bot/bot_filter.py
> +            '\033[38;5;216m USER ALREADY LIKED! Skipping. \033[0m')
Don't do coloring like this, see for example:
```python
self.console_print('info: account previously followed, skipping!', 'red')
```

2018-08-29 20:15 UTC, basnijholt commented on instabot/bot/bot_filter.py
> +def isInSkippedList(self, user_id):
remove this function because it is never used.

2018-08-29 20:15 UTC, basnijholt commented on instabot/bot/bot_filter.py
> +            '\033[38;5;216m USER ALREADY LIKED! Skipping. \033[0m')
also, remove this function because it is never used.

2018-08-29 20:15 UTC, basnijholt commented on instabot/bot/bot_filter.py
> +    if isInSkippedList(self, user_id):
remove this function because it is never used.

2018-08-29 20:15 UTC, basnijholt commented on instabot/bot/bot_filter.py
> +def isInLikedUsersList(self, user_id):
remove this function because it is never used.

2018-09-01 22:48 UTC, lukasz00500 commented
i just added this function because for now this bot is not checking if user is in liked.txt or skipped.txt before request to Instagram api. Scanning of this list should performed before downloading any data from user

2018-10-31 22:11 UTC, ohld commented
The code is obsolete, bug has been fixed in new version

2018-10-31 22:11 UTC, closed without merging