Upload resized video with thumbnail
ohld/igbot pull request #735
Opened 2019-01-12 17:35 UTC by maxpierini

New upload_video features
1. resize video (requires `ffmpeg` installed on OS)
2. thumbnail creation (requires ImageMagick `convert` installed on OS)

2019-01-13 18:31 UTC, ohld commented
LGTM. Thanks for the great work!

2019-01-13 18:32 UTC, ohld submitted a review, later dismissed

2019-01-13 18:36 UTC, ohld commented
Questions:
1) why do we need two video examples, not only one?
2) please add instructions how to install ffmpeg and convert libraries in the readme.md (use *.MD extension for files).

2019-01-13 18:42 UTC, maxpierini commented
> Questions:
> 
> 1. why do we need two video examples, not only one?
> 2. please add instructions how to install ffmpeg and convert libraries in the readme.md (use *.MD extension for files).

1. My fault... I thought I uploaded one horizontal and one vertical video. I uploaded two horizontal by mistake. I'll fix.
2. Ok :-)

2019-01-15 08:31 UTC, ohld requested changes
Last questions:
1) will this all works on windows?
2) can you please find the correspondent python packages that have the same functionallity as `ffmpeg` and `convert`? It is much easier for a user to just `pip install`something instead of installing of heavyweight external CLIs.

2019-01-15 08:31 UTC, ohld commented on examples/videos/README.md
> +  - Read here how to install `ffmpeg` https://github.com/adaptlearning/adapt_authoring/wiki/Installing-FFmpeg
hmmm,  can you please find a proper PIP package to simplify the installation? Being an instabot user it is quite easier to do `pip install python_magic_ffmpeg_package`.

2019-01-15 16:26 UTC, maxpierini commented on examples/videos/README.md
> +  - Read here how to install `ffmpeg` https://github.com/adaptlearning/adapt_authoring/wiki/Installing-FFmpeg
Closing pull request. New pull request from @maxdevblock using python modules only.

2019-01-15 16:26 UTC, maxpierini commented
Closing request. New pull request from @maxdevblock using python modules only.

2019-01-15 16:26 UTC, closed without merging

2019-01-16 15:46 UTC, ohld commented
Thanks! 
Great job and thanks for contributing. @maxpierini