Update get total followers or followings
ohld/igbot pull request #738
Opened 2019-01-13 16:32 UTC by maxdevblock

Updated `get_total_followers_or_followings` to include `to_file` option and users' filters.
Example included in _examples_ folder.

2019-01-13 18:27 UTC, ohld commented
LGTM

2019-01-20 11:56 UTC, ohld approved these changes

2019-01-20 11:56 UTC, ohld commented on instabot/api/api.py
> +                    if to_file is not None:
Ufff. I really don’t like this code. But for now I don’t have any idea how to improve it. Any from your side? Maybe it can be better with `with` construction?

2019-01-20 11:56 UTC, ohld commented on instabot/api/api.py
> +                    if to_file is not None:
@maxdevblock ?

2019-01-20 21:30 UTC, maxdevblock commented on instabot/api/api.py
> +                    if to_file is not None:
@ohld I'll work on it :-)

2019-01-20 22:52 UTC, ohld requested changes
Refine please the work with files to be more Pythonic

2019-01-22 14:39 UTC, ohld approved these changes

2019-01-22 14:56 UTC, merged