Added test unlike
ohld/igbot pull request #790
Opened 2019-01-24 17:06 UTC by maxdevblock

Added
`test_unlike`
`test_unlike_comment`
`test_unlike_medias`
`test_unlike_media_comments`
`test_unlike_user`

2019-01-25 10:11 UTC, sudoguy requested changes

2019-01-25 10:11 UTC, sudoguy commented on tests/test_bot_unlike.py
> +        for i, _ in enumerate(range(results)):
I suggest this
```suggestion
        for i in range(results):
```
because you don't use elements

2019-01-25 10:11 UTC, sudoguy commented on tests/test_bot_unlike.py
> +        for i, _ in enumerate(range(results)):
I suggest this
```suggestion
        for i in range(results):
```
because you don't use elements

2019-01-25 10:11 UTC, sudoguy commented on tests/test_bot_unlike.py
> +            ), json="{'status': 'ok'}", status=200
What if we get "feedback_required"? Apparently "unlike" not handle this situation.

2019-01-25 16:10 UTC, maxdevblock commented on tests/test_bot_unlike.py
> +            ), json="{'status': 'ok'}", status=200
I need to run some stress test for unlike. Didn't try it, I don't know if feedback is returned for too many unlikes too.

2019-01-27 23:44 UTC, ohld approved these changes

2019-01-27 23:44 UTC, ohld commented
@sudoguy merge?

2019-01-30 08:23 UTC, merged