fix upload photo WinError 32
ohld/igbot pull request #825
Opened 2019-02-23 19:24 UTC by trebacz626

Fix for issue #807

2019-02-24 13:03 UTC, smolyakov26 approved these changes

2019-02-24 13:31 UTC, smolyakov26 requested changes
1
2019-02-24 16:29:36,399 - INFO - Logged-in successfully as 'alx_smolyakov'!
upload: First test
Analizing `./pics\1 First test.jpg`
FOUND w:834, h:720, ratio=1.1583333333333334
Horizontal image
Saving new image w:834 h:720 to `./pics\1 First test.jpg.CONVERTED.jpg`
FOUND: w:834 h:720 r:1.1583333333333334
[WinError 32] Процесс не может получить доступ к файлу, так как этот файл занят другим процессом: './pics\\1 First test.jpg.CONVERTED.jpg' -> './pics\\1 First test.jpg.CONVERTED.jpg.REMOVE_ME'
upload: First test
Analizing `./pics\1 First test.jpg`
FOUND w:834, h:720, ratio=1.1583333333333334
Horizontal image
Saving new image w:834 h:720 to `./pics\1 First test.jpg.CONVERTED.jpg`
FOUND: w:834 h:720 r:1.1583333333333334
[WinError 32] Процесс не может получить доступ к файлу, так как этот файл занят другим процессом: './pics\\1 First test.jpg.CONVERTED.jpg' -> './pics\\1 First test.jpg.CONVERTED.jpg.REMOVE_ME'

2019-02-24 15:21 UTC, trebacz626 commented
Sorry, it's my first Pull Request. I think I've messed sth with branches. Could you check if those lines have changed in your function. I'm asking because I copied this project again to see if I get any error and I got the same as you, but then I switched branch to fix-WinError32-photo-upload and everything worked properly.

2019-02-24 16:05 UTC, smolyakov26 commented
Cheked those lines , it changed, but still getting that error (

вс, 24 фев 2019 г., 18:21 trebacz626 <notifications@github.com>:

> Sorry, it's my first Pull Request. I think I've messed sth with branches.
> Could you check if those lines have changed in your function. I'm asking
> because I copied this project again to see if I get any error and I got the
> same as you, but then I switched branch to fix-WinError32-photo-upload and
> everything worked properly.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/instagrambot/instabot/pull/825#issuecomment-466786062>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/Aq9JkjqPWh01ji1WIIarXMgn8uP_bbU_ks5vQq3fgaJpZM4bOHQ2>
> .
>

2019-02-25 10:28 UTC, smolyakov26 commented
which script do you use ? autopost or photo ?

2019-02-25 10:35 UTC, trebacz626 commented
I tested both. Python version: 3.7.2

2019-02-25 10:56 UTC, smolyakov26 requested changes
still getting ducking error Win32, as far as i understand it cant manage converted image.

2019-02-25 11:12 UTC, ohld approved these changes

2019-02-25 11:12 UTC, ohld commented on instabot/api/api_photo.py
> +    photoFile =open(photo, 'rb')
you should use this construction:
``` python
with open(photo, 'rb') as photofile:
  <your code here>
```

2019-02-25 11:27 UTC, smolyakov26 requested changes
`C:\Users\фдуч\Desktop\instabot-master\examples\photos/media/Chrysanthemum.jpg.CONVERTED.jpg

may be it caused by the way to the file , it says the location that not exist on windows cant be reacheable...
MB its all abot SLASHES and BACKSLASHES ?

2019-02-25 14:13 UTC, lmgtrigo commented
Same error...
[WinError 32] The process cannot access the file because it is being used by another process: './pics\\1 First test.jpg.CONVERTED.jpg' -> './pics\\1 First test.jpg.CONVERTED.jpg.REMOVE_ME'

2019-04-26 18:08 UTC, ohld approved these changes

2019-04-27 18:01 UTC, merged