Implemented Story Download
ohld/igbot pull request #876
Opened 2019-04-22 08:45 UTC by marco2012

Story download is now fully functional with the simple command `bot.download_stories("username")` as shown in the example folder.

2019-04-22 12:57 UTC, ohld commented
Great! Thank you very much! Can you please fix the TRAVIS-CI codestyle issues? Thanks

2019-04-25 17:40 UTC, marco2012 commented
I added support for liking images based on a given location with the function `bot.like_location_feed("location name", amount)`, as shown in the example folder.

2019-04-28 19:53 UTC, marco2012 commented
I added support for approving or rejecting pending follow requests for private accounts.

2019-04-29 07:46 UTC, ohld commented
Man, I really appreciate your work, but I can not approve your pull request since you've changed the Readme.md file. Please remove changes to this file and I'll approve the PR

2019-04-29 07:47 UTC, ohld requested changes
Don't change Readme.md file

2019-04-29 07:47 UTC, ohld commented on README.md
> +# Instabot with Stories support
I don't think we need to rename the tagline, please remove it from the Pull Request

2019-04-29 07:47 UTC, ohld commented on examples/download_stories.py
> +bot.download_stories("") #INSERT USERNAME HERE
username should be taken from command line arguments

2019-04-29 07:47 UTC, ohld commented on instabot/api/api_story.py
> +    p = "stories/"+username
codestyle!

2019-04-29 07:47 UTC, ohld commented on examples/comment_medias_by_location.py
> +w# coding=utf-8
???????????????????

2019-04-29 07:47 UTC, ohld commented on README.md
> +# Instabot with Stories support
Please remove it

2019-04-29 07:47 UTC, ohld commented on examples/download_stories.py
> +bot.download_stories("")  # INSERT USERNAME HERE
Make this username be inserted by command line arguments, you've already had the code that parses the CLI input

2019-04-29 08:05 UTC, marco2012 commented on instabot/api/api_story.py
> +    p = "stories/"+username
I'm not sure what you mean here, all the tests on codestyle succeed

2019-04-29 08:05 UTC, marco2012 commented
Everything should be resolved, I switched to the original readme

2019-04-29 08:06 UTC, marco2012 commented on examples/download_stories.py
> +bot.download_stories("") #INSERT USERNAME HERE
added command line argument

2019-04-29 08:09 UTC, marco2012 commented on README.md
> +# Instabot with Stories support
switched to original readme

2019-04-29 08:09 UTC, marco2012 commented on examples/comment_medias_by_location.py
> +w# coding=utf-8
keyboard mistake, removed it

2019-04-29 08:12 UTC, marco2012 commented on examples/download_stories.py
> +bot.download_stories("")  # INSERT USERNAME HERE
added parser in all my examples

2019-04-29 08:52 UTC, ohld commented
One last question about `.gitignore`: why have you added a new file to it?

2019-04-29 09:00 UTC, marco2012 commented
restored original `.gitignore`

2019-04-29 09:03 UTC, ohld approved these changes

2019-04-29 09:03 UTC, ohld commented on .gitignore
> +tests.txt
why have you added this to the main repo?

2019-04-29 09:05 UTC, ohld commented
Thank you very much for your work! I think your new functionality can be very useful for users.

2019-04-29 09:05 UTC, merged