add feedliker example
ohld/igbot pull request #99
Opened 2017-03-07 20:35 UTC by maxkrivich

2017-03-07 21:05 UTC, stasfilin requested changes
Check my comment

2017-03-07 21:05 UTC, stasfilin commented on examples/infinity_feedliker_example.py
> +	time.sleep(1*60)
1*60?

you can use:
```python
time.sleep(60)
```

2017-03-08 08:03 UTC, maxkrivich commented on examples/infinity_feedliker_example.py
> +	time.sleep(1*60)
@stasfilin ok, what I must write if I want 2 mins 120 or 2*60, of 3 min 180(3*60) what most user friendly?

2017-03-08 14:59 UTC, stasfilin commented on examples/infinity_feedliker_example.py
> +	time.sleep(1*60)
@maxkrivich if 2 or more mins its okay to use 2*60 or something like this.
Also, if you want to use min, use variable for this, for example

```python
wait = 2*60 # Minutes to seconds
time.sleep(wait)
```
Make sense?

2017-03-08 20:09 UTC, stasfilin commented
@maxkrivich Any progress?

2017-03-11 06:39 UTC, merged